# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty


# Setup
title:            Zina Astafyeva
tagline:          'Web Developer'
description:      'Web Developer'
url:              https://tragetraje.github.io
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0
gems: [jekyll-paginate, jemoji]


github:
  repo:           https://github.com/tragetraje
